global: 
  applicationName: notes
  region: us-central1
image:
  name: gcr.io/g5-images/annotation
configurations:
  staging:
    configMapData:
      BROWSER_URL: 'https://notes-opex-staging.g5devops.com'
      GA_PROPERTY: ''
      CRS_URL: ''
      G5_AUTH_ENDPOINT: https://auth.g5search.com/oauth/authorize
      G5_TOKEN_ENDPOINT: https://auth.g5search.com/oauth/token
      G5_AUTH_REDIRECT_URI: https://notes-opex-staging.g5devops.com/g5_auth/users/auth/g5/callback
      G5_AUTH_ME_ENDPOINT: https://auth.g5search.com/v1/me
  prime:
    configMapData:
      BROWSER_URL: 'https://notes-opex-prime.g5devops.com'
      GA_PROPERTY: ''
      CRS_URL: ''
      G5_AUTH_ENDPOINT: https://auth.g5search.com/oauth/authorize
      G5_TOKEN_ENDPOINT: https://auth.g5search.com/oauth/token
      G5_AUTH_REDIRECT_URI: https://notes-opex-prime.g5devops.com/g5_auth/users/auth/g5/callback
      G5_AUTH_ME_ENDPOINT: https://auth.g5search.com/v1/me
  production:
    configMapData:
      BROWSER_URL: 'https://notes-opex-staging.g5devops.com'
      GA_PROPERTY: ''
      CRS_URL: ''
      G5_AUTH_ENDPOINT: https://auth.g5search.com/oauth/authorize
      G5_TOKEN_ENDPOINT: https://auth.g5search.com/oauth/token
      G5_AUTH_REDIRECT_URI: https://notes-opex-staging.g5devops.com/g5_auth/users/auth/g5/callback
      G5_AUTH_ME_ENDPOINT: https://auth.g5search.com/v1/me
activeCloudSQLSubchart: "cloud-sql"
activeBullSubchart: "memorystore"
cloud-sql: 
  databaseVersion: POSTGRES_11
memorystore: 
  purpose: bull
  tier: BASIC
  # memorySizeGb: 1