apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    {{ include "notes.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/search: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: 1
  selector:
    matchLabels:
      {{ include "notes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: node
      labels:
        {{ include "notes.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-logs-container: node
    spec:
      serviceAccountName: {{ include "notes.serviceAccountName" . }}
      containers:
        - name: node
          ports:
            - name: http
              containerPort: 8085
          #livenessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: http
          image: {{ .Values.image.name }}:{{ required "image.tag is required" .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 300Mi
          env:
            - name: BROWSER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: BROWSER_URL
            - name: CRS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: CRS_URL
            - name: G5_AUTH_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: G5_AUTH_ENDPOINT
            - name: G5_TOKEN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: G5_TOKEN_ENDPOINT
            - name: G5_AUTH_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: G5_AUTH_REDIRECT_URI
            - name: G5_AUTH_ME_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: G5_AUTH_ME_ENDPOINT
            - name: GA_PROPERTY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: GA_PROPERTY
            - name: GKE
              value: "true"
            - name: INCLUDE_G5_UPDATABLES
              value: "true"
            - name: INCLUDE_G5_AUTH
              value: "true"
            - name: DATABASE_DIALECT
              value: postgres
            - name: DATABASE_IDLE
              value: "10000"
            - name: DATABASE_AQUIRE
              value: "10000"
            - name: DATABASE_EVICT
              value: "10000"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_MAX_CONNECTIONS
              value: "50"
            - name: DATABASE_MIN_CONNECTIONS
              value: "0"
            - name: DATABASE_SSL
              value: "false"
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "cloudsql.hostConfigMapName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
                  key: {{ include "cloudsql.hostConfigMapKey" . }}
            - name: DATABASE_NAME
              value: {{ include "cloudsql.databaseName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
            - name: DATABASE_USER
              value: {{ include "cloudsql.userName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudsql.passwordSecretName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeCloudSQLSubchart)) }}
                  key: {{ include "cloudsql.passwordSecretKey" . }}
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "redis.urlConfigMapName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeBullSubchart)) }}
                  key: {{ include "redis.urlConfigMapKey" . }}
            - name: DATABASE_URL
              value: $(DATABASE_DIALECT)://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
            - name: G5_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: G5_AUTH_CLIENT_ID
            - name: G5_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: G5_AUTH_CLIENT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: SESSION_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: JWT_SECRET
            - name: SF_USERNAME
              valueFrom:
                  secretKeyRef:
                    name: annotation
                    key: SF_USERNAME
            - name: SF_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: SF_PASSWORD
            - name: SF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: SF_TOKEN
            - name: SLACK_FEEDBACK_URL
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: SLACK_FEEDBACK_URL
            - name: DAM_DATABASE_MAX_CONNECTIONS
              value: "5"
            - name: DAM_DATABASE_MIN_CONNECTIONS
              value: "0"
            - name: DAM_DATABASE_IDLE
              value: "10000"
            - name: DAM_DATABASE_AQUIRE
              value: "30000"
            - name: DAM_DATABASE_EVICT
              value: "10000"
            - name: DAM_DATABASE_LOGGING
              value: "false"
            - name: DAM_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: annotation
                  key: DAM_DATABASE_URL